# fly.toml app configuration file generated for warcop on 2023-05-31T05:57:57+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "warcop"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
